package com.example.turf_Backend.enums;

public enum RefundReason {
    CUSTOMER_CANCELLED_BEFORE_CUTOFF,
    OWNER_CANCELLED_BEFORE_SLOT,
    ADMIN_CANCELLED_EMERGENCY,

    SLOT_UNAVAILABLE_AFTER_PAYMENT,
    PAYMENT_CAPTURE_ERROR,
    DUPLICATE_PAYMENT
}
